module.exports = [
    {name: "Mary", age: 20, email: "marya@gram.com"},
    {name: "Edwards", age: 34, email: "edwards@gram.com"},
    {name: "Loveth", age: 45, email: "loveth@gram.com"},
    {name: "John", age: 28, email: "john@gram.com"},
    {name: "Emily", age: 22, email: "emily@gram.com"},
    {name: "Michael", age: 40, email: "michael@gram.com"},
    {name: "Sophia", age: 25, email: "sophia@gram.com"},
    {name: "Daniel", age: 31, email: "daniel@gram.com"},
    {name: "Olivia", age: 29, email: "olivia@gram.com"},
    {name: "David", age: 50, email: "david@gram.com"},
    {name: "Emma", age: 26, email: "emma@gram.com"},
    {name: "William", age: 38, email: "william@gram.com"},
    {name: "Ava", age: 33, email: "ava@gram.com"},
    {name: "Christopher", age: 35, email: "christopher@gram.com"},
    {name: "Mia", age: 27, email: "mia@gram.com"},
    {name: "Ethan", age: 32, email: "ethan@gram.com"},
    {name: "Isabella", age: 30, email: "isabella@gram.com"},
    {name: "James", age: 42, email: "james@gram.com"},
    {name: "Grace", age: 23, email: "grace@gram.com"},
    {name: "Benjamin", age: 36, email: "benjamin@gram.com"},
    {name: "Lily", age: 21, email: "lily@gram.com"},
    {name: "Alexander", age: 48, email: "alexander@gram.com"},
    {name: "Chloe", age: 24, email: "chloe@gram.com"},
    {name: "Ryan", age: 39, email: "ryan@gram.com"},
    {name: "Madison", age: 37, email: "madison@gram.com"},
];